apiVersion: v1
baseDomain: hackfest
metadata:
  name: ocp
networking:
  machineCIDR: 192.168.123.0/24
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.123.8
    ingressVIP: 192.168.123.9
    provisioningBridge: provisioning
    provisioningNetworkCIDR: 172.22.0.0/24
    provisioningNetworkInterface: ens3
    hosts:
      - name: master-0
        role: master
        bmc:
          address: ipmi://192.168.123.248
          username: admin
          password: CNV25h@ck
        bootMACAddress: de:ad:be:ef:03:00
      - name: master-1
        role: master
        bmc:
          address: ipmi://192.168.123.249
          username: admin
          password: CNV25h@ck
        bootMACAddress: de:ad:be:ef:03:01
      - name: master-2
        role: master
        bmc:
          address: ipmi://192.168.123.250
          username: admin
          password: CNV25h@ck
        bootMACAddress: de:ad:be:ef:03:02
      - name: worker-0
        role: worker
        bmc:
          address: ipmi://192.168.123.251
          username: admin
          password: CNV25h@ck
        bootMACAddress: de:ad:be:ef:04:00
      - name: worker-1
        role: worker
        bmc:
          address: ipmi://192.168.123.252
          username: admin
          password: CNV25h@ck
        bootMACAddress: de:ad:be:ef:04:01
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2ljcGlsY2hlcjFlNjV1eTlkNjJibXFtYmludWR1MmF3dWswYzpMNVhRWlQ5SzNDQ0JFWVVaMVdQWUFRU0hGRDVXMzYxSzE5MURNQkNMTkw2SVRMM01KQjk4MjNDRE5JRlhPN0JD","email":"ipilcher@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2ljcGlsY2hlcjFlNjV1eTlkNjJibXFtYmludWR1MmF3dWswYzpMNVhRWlQ5SzNDQ0JFWVVaMVdQWUFRU0hGRDVXMzYxSzE5MURNQkNMTkw2SVRMM01KQjk4MjNDRE5JRlhPN0JD","email":"ipilcher@redhat.com"},"registry.connect.redhat.com":{"auth":"NDU2NzA4M3x1aGMtMWU2NXVZOWQ2MkJtcW1iSU5VRFUyQVd1azBjOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJd09XSmtNV1k0TlRFMU5UWTBZems0T1dZek4yVTVNR1l6TlROaVptSXhPQ0o5LkNhdW5ERE9ZMF9TbjUzQzhUUUJKcDNHRUJjVC1TTWdLRzNVVVk5Sjg2NE5BZm83a0F3eTZ3RWYwNHBPRHRHX0NtSGpFb2dOMmJlRFJaYWFvSm82a2x3QVZ6MnoyRXFsREFHZHJSZWJXNTIyUWtVdGpDMndfR3ROZFUtY2JDNVBHVndZS0V3OGFRU1NpV3h5NWhHOUI1SHdwU3o0Smp5cDU0ZGE5Zkp2c0NTZ2ExWUlwRzY1OG01dUR1c3ZRR2xjUkxhQjNCcWxFckU0YU9zZlpzcEJCejNSOU1FV0JTSExaSTRYSXFqZ2Z0Y1A0OHNzYVN2RW1KRnZDSUxVWk1wLVZHM2wtd25LUnlaZjVSd0otdjdTRFpDYVI1SG1FcXZDcUZxbVpWb2g4UzZaUXEteTFwRmhQUkhpblRyVGw2S0VVLUQ3NXdieW9LN21nU0djdTcxZjFmc3o4Y1FPNUhMMXdxcmRrNUFjVnZOaVQtWnVTV1lLNWI0LVJLSUx3bHFsMzVnMkVoRXRhb0lwOGU2a0tMellfSFBwdldZTDREWmIweDhsZlpxaEswaHFHRTZJa2JyaUp4b1JsN20tX0JWZFhXekRMMk8xZkhITzRfMjhZYWkzM0xlSnN1TGpoZmZ5Wkt6UmM2WXJYVmdqZ0hzUDN2aktibXNCMjJ3ZW5saHRtaFA2aEFCOGVram9rMjI4N0w3dFFOUkl5X2FWTjJKckRDckthd2taa0ZvbnVEcnN4QXd5X2pVZHNIc1JoMUxhZ283TWVPd3BiUlF2emFFSmwycl9NYmNyU0pTdzB2SW1STTRsOGprXzNqcVVpS1VreE14MHNVNGh6di1ONnZYdXQ0TEFnQk0yOTRSOXpVRVBsU0ZPQzgxX2NEdDJreWRRa1FsUHd4WWxvRGhB","email":"ipilcher@redhat.com"},"registry.redhat.io":{"auth":"NDU2NzA4M3x1aGMtMWU2NXVZOWQ2MkJtcW1iSU5VRFUyQVd1azBjOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJd09XSmtNV1k0TlRFMU5UWTBZems0T1dZek4yVTVNR1l6TlROaVptSXhPQ0o5LkNhdW5ERE9ZMF9TbjUzQzhUUUJKcDNHRUJjVC1TTWdLRzNVVVk5Sjg2NE5BZm83a0F3eTZ3RWYwNHBPRHRHX0NtSGpFb2dOMmJlRFJaYWFvSm82a2x3QVZ6MnoyRXFsREFHZHJSZWJXNTIyUWtVdGpDMndfR3ROZFUtY2JDNVBHVndZS0V3OGFRU1NpV3h5NWhHOUI1SHdwU3o0Smp5cDU0ZGE5Zkp2c0NTZ2ExWUlwRzY1OG01dUR1c3ZRR2xjUkxhQjNCcWxFckU0YU9zZlpzcEJCejNSOU1FV0JTSExaSTRYSXFqZ2Z0Y1A0OHNzYVN2RW1KRnZDSUxVWk1wLVZHM2wtd25LUnlaZjVSd0otdjdTRFpDYVI1SG1FcXZDcUZxbVpWb2g4UzZaUXEteTFwRmhQUkhpblRyVGw2S0VVLUQ3NXdieW9LN21nU0djdTcxZjFmc3o4Y1FPNUhMMXdxcmRrNUFjVnZOaVQtWnVTV1lLNWI0LVJLSUx3bHFsMzVnMkVoRXRhb0lwOGU2a0tMellfSFBwdldZTDREWmIweDhsZlpxaEswaHFHRTZJa2JyaUp4b1JsN20tX0JWZFhXekRMMk8xZkhITzRfMjhZYWkzM0xlSnN1TGpoZmZ5Wkt6UmM2WXJYVmdqZ0hzUDN2aktibXNCMjJ3ZW5saHRtaFA2aEFCOGVram9rMjI4N0w3dFFOUkl5X2FWTjJKckRDckthd2taa0ZvbnVEcnN4QXd5X2pVZHNIc1JoMUxhZ283TWVPd3BiUlF2emFFSmwycl9NYmNyU0pTdzB2SW1STTRsOGprXzNqcVVpS1VreE14MHNVNGh6di1ONnZYdXQ0TEFnQk0yOTRSOXpVRVBsU0ZPQzgxX2NEdDJreWRRa1FsUHd4WWxvRGhB","email":"ipilcher@redhat.com"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDmkzAV/xlIfWY8U2b2VVlLqz86ngRu6v6sMjDBAEHW6Ju81wppl363Q31t4Cd+qz63KGbh9zRMSp8vaB/I/O+GuYL/Qir8ulHsFRkxawPUh0ILKjolVYoZgGQ6P4NttpdIrjq15PP8c0ACY/V63kegh1Comudm76BjRB6UwJYr3b2GgH9cCh3hSEgJ/zzF2htixN4i8hhXEgpigh0RvFWg5rzwxECmXOeEBhGPJMEAuBFAOxLsoqK8gVmkdDXbFDI28iHFHxbQdtZ5hlQtWxfq5I9XBUyyl7FBIS1gEvkfCFBbD9TfZfOOjIfl0tWqXYuOrr1F+2B4LXD4QLOUR4gw4Safxu+rJqvz4uRnW/XyGBvXFNJKJa9Llxgap4hymnP2XDJaG1R6uIMBxc/l2LUWKap03ZXQia5enqYDZBdw4drag3VAZky+xMaq79/SyAMWiNw0CBUFf48j5NUrFS24IfqBDqT4OQcDn+43f+lw8esN3UNRKu058c4+00+3010= kni@prov.ocp.hackfest'
